### ISSUE TITLE
Allow training hours to be submitted

### ISSUE THREAD

**Issue by ThorpeJosh** [ThorpeJosh/tp-timesheet#59]
Current behaviour is all hours are allocated to 'live'.

TODO:
- Create a cli option to allow hours to be allocated to training if needed eg. `--training 8` ?
- Update the form submission to allow inputing a non-0 value for the training field

**Comment by changukshin** [comment]
I'd write down some opinion for this issue. plz consider.

This application supports either
- [1]: submission of timesheet from `start_date` to `end_date`.
- [2]: automated submission of timesheet for everyday

For now, I assume that the most likely option of submission is `live`. So that the default option for `task` is `live`.
And for [1] above, I think this cmd would make sense.
```
$tp-timesheet -s today (--live is omitted, default)
$tp-timesheet -s 1/12/22 --training 8
$tp-timesheet -s today -c 5 --training 8
$tp-timesheet -s today -c 5 --live 8 (stating `--live` is supported)
$tp-timesheet -s today -c 5 (--live is omitted, default)
```

for [2]
```
$tp-timesheet -a --training 8
$tp-timesheet -a --live 8 (stating `--live` is supported)
$tp-timesheet -a (--live is omitted, default)
```

**And, `--hours` option would be deprecated as `--(training|live|idle|issue)` option substitutes the `--hours` option.**
**After certain period of the time, `--hours` options will be removed.**
**Until that, `--hours` would be treated as the synonym of `--live`.**

Submission of more than two tasks per a single day(ex, `--training 4` `--live 4`) is not supported or processed by this issue and PR.

As this issue update the behaviour of current cli argument, I think it requires discussion.
any other opinions are welcome as always.

CC @ThorpeJosh @siewyeng @lamchuntat

**Comment by siewyeng** [comment]
This issue is also partially addressed in #85 but only for the clockify portion (sorry for the mess). In the PR, I added args for the task type (with project type also) but the number of hours portion is not supported yet. --> e.g., `tp-timesheet -a --task "Training hours"` will automate 8 hour training days.

As @changukshin mentioned, the submission of more than one task per day is also not supported and but this may be an issue worth considering in @lamchuntat 's PR #83

**Comment by changukshin** [comment]
@siewyeng Sorry, I didn't follow up those PRs. Let's postpone this issue/PR until those PRs are merged. btw, I don't think you messed anything. No stress at all.

**Comment by ThorpeJosh** [comment]
Agree with your input @changukshin. Things get more complicated now with more options needing to be supported.

We also need `OOO|Holiday|etc` but these can only be applied to clockify.

Half-day now requires `--live 4 --ooo 4`

**Comment by changukshin** [comment]
@ThorpeJosh 
Thanks for the remind of 'OOO/Holiday/etc'.
This thread I want to process both clockify and timesheet to support to accept the `task` name on the submission.
I would suggest that the process of 'supporting half-day' would be held on another thread/PR.
